#!/bin/sh
# Requires node.js: sudo pacman -Sy nodejs

if [ $# -lt 1 ]; then
    echo "Usage: $(basename "$0") FILE [FILE...]" >&2
    exit 1
fi

result=0
for f in "$@"; do
    pomf_reply="$(curl -sS --progress-bar -F "files[]=@$f" http://pomf.se/upload.php)"
    if [ $? != 0 ]; then
        echo "Failed to upload $f" >&2
        result=1
    else
        pomf_id=$(node -pe "JSON.parse(process.argv[1]).files[0].url" "$pomf_reply")
        if [ $? != 0 ]; then
            echo "Failed to parse uploader response to $f" >&2
            printf "Response:\n%s\n" "$pomf_reply" >&2
            result=1
        fi

        if [ $# -gt 1 ]; then
            printf "%s: " "$f"
        fi

        echo "http://a.pomf.se/$pomf_id"
    fi
done
exit $result
