#!/bin/sh

if [ "$1" = --uguu ]; then
    upload=uguuload
    title='Uguu~'
else
    upload=pomfload
    title='Pomf!'
fi

lock="/tmp/pomfclip-$DISPLAY"
exec 4>"$lock"
if flock -n 4; then
    file=""
    errorfile=""
    cleanup() {
        code=$?
        [ -n "$file" ] && rm -f -- "$file"
        [ -n "$errorfile" ] && rm -f -- "$errorfile"
        rm -f -- "$lock"
        trap - EXIT INT HUP QUIT TERM
        exit "$code"
    }
    trap cleanup EXIT INT HUP QUIT TERM

    file=$(mktemp --tmpdir pomfXXXXXXXX.png)
    errorfile=$(mktemp --tmpdir pomfXXXXXXXX.log)

    log() {
        local level
        level="$1"
        shift
        echo >&2 "$@"
        notify-send -i dialog-"$level" "$title" "$*" &
    }

    die() {
        log "$@"; exit 1
    }

    if [ -n "$SCREENSHOT_TOOL" ]; then
        "$SCREENSHOT_TOOL" "$file"
    elif command -v shutter >/dev/null 2>&1; then
        shutter -e -s -o "$file"
    elif command -v gnome-screenshot >/dev/null 2>&1; then
        gnome-screenshot -a -f "$file"
    elif command -v scrot >/dev/null 2>&1; then
        i=0
        while [ $i -lt 10 ]; do
            out=$(scrot -s "$file" 2>&1)
            # Workaround for scrot stupidness: if it fails because the pointer is "temporarily unavailable", sleep then retry
            [ $? = 0 ] && break || case "$out" in
                *"Resource temporarily unavailable"*) sleep 0.1;;
                *) break;;
            esac
            i=$((i+1))
        done
    elif command -v import >/dev/null 2>&1; then
        import "$file"
    else
        die error "No screenshot software?"
    fi

    [ $? != 0 -a $? != 2 ] && die error "Failed to take a screenshot"
    [ ! -s "$file" ] && die warning "Did not take a screenshot"

    optipng "$file"

    url=$("$upload" "$file" 2>$errorfile) || die warning "Failed to upload screenshot.$(echo;cat "$errorfile")"

    echo "$url"

    if
        printf %s "$url" | xsel -ib
        printf %s "$url" | xsel -ip
    then
        log information "Uploaded screenshot at $url! The URL is in your clipboard."
    else
        log information "Uploaded screenshot at $url!"
    fi
fi
