#!/bin/sh
# Requires node.js: sudo pacman -Sy nodejs

if [ "$#" -lt 1 ]; then
    echo "Usage: $(basename "$0") FILE [FILE...]" >&2
    exit 1
fi

result=0
for f do
    if ! pomf_reply="$(curl -sS --progress-bar -F "files[]=@$f" http://pomf.se/upload.php)"; then
        echo "Failed to upload $f" >&2
        result=1
    else
        if ! pomf_id=$(node -pe "JSON.parse(process.argv[1]).files[0].url" "$pomf_reply"); then
            echo "Failed to parse uploader response to $f" >&2
            printf "Response:\n%s\n" "$pomf_reply" >&2
            result=1
        fi

        if [ "$#" -gt 1 ]; then
            printf "%s: " "$f"
        fi

        echo "http://a.pomf.se/$pomf_id"
        printf '%s\t%s\t%s\n' "$(date --rfc-3339=seconds)" "http://a.pomf.se/$pomf_id" "$f" >> ~/.pomf_history
    fi
done
exit "$result"
