#!/bin/sh
if [ "$#" -lt 1 ]; then
    echo "Usage: $(basename -- "$0") FILE [FILE...]" >&2
    exit 1
fi

if tty > /dev/null; then
    show_progress=--progress-bar
else
    show_progress=
fi

result=0
for f do
    if ! url="$(curl -sS $show_progress -F randomname=yes -F "file=@$f" 'https://uguu.se/api.php?d=upload')"; then
        echo "Failed to upload $f" >&2
        printf %s\\n "$url" >&2 # Maybe it contains some error message now?
        result=1
    else
        [ "$#" -gt 1 ] && printf "%s: " "$f"

        [ "${url#http:}" != "$url" ] && url=https${url#http}
        echo "$url"
        printf '%s\t%s\t%s\n' "$(date --rfc-3339=seconds)" "$url" "$f" >> ~/.pomf_history
    fi
done
exit "$result"
