#!/bin/sh
usage() {
    echo "Usage: $(basename -- "$0") [--upload URL] [--download download-url-prefix] [--[no-]progress] [--] FILE [FILE...]" >&2
}

[ "$#" -lt 1 ] && { usage; exit 1; }

if tty > /dev/null; then
    show_progress=--progress-bar
else
    show_progress=
fi

upload_url='https://uguu.se/api.php?d=upload-tool'
download_url=

eval "set -- $(getopt -n "$0" -o u:d:pn -l upload:,download:,progress,no-progress -- "$@")"
while [ "$#" != 0 ]; do
    case $1 in
        --upload|-u)      upload_url=$2; shift;;
        --download|-d)    download_url=$2; shift;;
        --progress|-p)    show_progress=--progress-bar;;
        --no-progress|-n) show_progress=;;
        --) break;;
        *) usage; exit 1;;
    esac; shift
done; shift

result=0
for f do
    if ! url="$(curl -sS $show_progress -F randomname=yes -F "file=@$f" "${upload_url:?}")"; then
        echo "Failed to upload $f" >&2
        printf %s\\n "$url" >&2 # Maybe it contains some error message now?
        result=1
    else
        url=$download_url$url

        [ "$#" -gt 1 ] && printf "%s: " "$f"
        printf %s\\n "$url"

        printf '%s\t%s\t%s\n' "$(date --rfc-3339=seconds)" "$url" "$f" >> ~/.pomf_history
    fi
done
exit "$result"
